version: '3'
services: 
  oracle-db:
    image: gvenzl/oracle-xe:18.4.0-slim
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: Admin1234
    restart: always
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./initdb:/container-entrypoint-initdb.d
    
volumes:
  oracle-data:
    driver: local
    
